## Hyperparameters
seed: 2025
start_lr: 5e-3
Epoch: 1000
batch_size: 4
weight_decay: 0.001
N : 600
workers: 16
initial_checkpoint: 'None'
##Foundation model
fundation_path_feature_HMUCH: 'HMUCH UNI.pkl'
fundation_path_feature_TMUGH: 'TMUGH UNI.pkl'
fundation_path_feature_CHCAMS: 'CHCAMS UNI.pkl'

##Cohort
Train_cohort: "Train.csv"
Val_cohort: "Test.csv"
HMUCH_cohort: "HMUCH.csv"
TMUGH_cohort: "MUGH.csv"


##model 存储位置
out_dir: "Result/"



